baseURL = "http://tanakahx.com/"
languageCode = "en-us"
title = "tanakahx.com"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Your site description"
  copyright = "Copyright © 2020 Hiroyuki Tanaka"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:year/:month/:day/:filename/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
